[2024-10-23T02:09:26.926+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-23T02:09:26.945+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_data_dump_dag.transform_data manual__2024-10-23T00:40:15.230222+00:00 [queued]>
[2024-10-23T02:09:26.957+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_data_dump_dag.transform_data manual__2024-10-23T00:40:15.230222+00:00 [queued]>
[2024-10-23T02:09:26.958+0000] {taskinstance.py:2865} INFO - Starting attempt 4 of 6
[2024-10-23T02:09:26.988+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform_data> on 2024-10-23 00:40:15.230222+00:00
[2024-10-23T02:09:27.056+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3199) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-23T02:09:27.040+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nyc_taxi_data_dump_dag', 'transform_data', 'manual__2024-10-23T00:40:15.230222+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_data_dag.py', '--cfg-path', '/tmp/tmp6joks4rm']
[2024-10-23T02:09:27.058+0000] {standard_task_runner.py:72} INFO - Started process 3224 to run task
[2024-10-23T02:09:27.058+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask transform_data
[2024-10-23T02:09:27.258+0000] {task_command.py:467} INFO - Running <TaskInstance: nyc_taxi_data_dump_dag.transform_data manual__2024-10-23T00:40:15.230222+00:00 [running]> on host c9968e9c0757
[2024-10-23T02:09:27.534+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saba' AIRFLOW_CTX_DAG_ID='nyc_taxi_data_dump_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T00:40:15.230222+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-23T00:40:15.230222+00:00'
[2024-10-23T02:09:27.538+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-23T02:09:46.962+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-23T02:09:47.318+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-23T02:09:47.331+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nyc_taxi_data_dump_dag, task_id=transform_data, run_id=manual__2024-10-23T00:40:15.230222+00:00, execution_date=20241023T004015, start_date=20241023T020926, end_date=20241023T020947
[2024-10-23T02:09:48.030+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-23T02:09:48.272+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-23T02:09:48.280+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
