[2024-10-23T02:11:41.490+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-23T02:11:41.510+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_data_dump_dag.load_data manual__2024-10-23T00:40:15.230222+00:00 [queued]>
[2024-10-23T02:11:41.525+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_data_dump_dag.load_data manual__2024-10-23T00:40:15.230222+00:00 [queued]>
[2024-10-23T02:11:41.526+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 4
[2024-10-23T02:11:41.558+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data> on 2024-10-23 00:40:15.230222+00:00
[2024-10-23T02:11:41.618+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3330) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-23T02:11:41.598+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nyc_taxi_data_dump_dag', 'load_data', 'manual__2024-10-23T00:40:15.230222+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_data_dag.py', '--cfg-path', '/tmp/tmptgu18_l3']
[2024-10-23T02:11:41.620+0000] {standard_task_runner.py:72} INFO - Started process 3350 to run task
[2024-10-23T02:11:41.621+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask load_data
[2024-10-23T02:11:41.816+0000] {task_command.py:467} INFO - Running <TaskInstance: nyc_taxi_data_dump_dag.load_data manual__2024-10-23T00:40:15.230222+00:00 [running]> on host c9968e9c0757
[2024-10-23T02:11:41.998+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saba' AIRFLOW_CTX_DAG_ID='nyc_taxi_data_dump_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T00:40:15.230222+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-23T00:40:15.230222+00:00'
[2024-10-23T02:11:42.006+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-23T02:11:42.275+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-23T02:11:42.289+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-23T02:11:42.290+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nyc_taxi_data_dump_dag, task_id=load_data, run_id=manual__2024-10-23T00:40:15.230222+00:00, execution_date=20241023T004015, start_date=20241023T021141, end_date=20241023T021142
[2024-10-23T02:11:42.325+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-23T02:11:42.342+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-23T02:11:42.343+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
